### ISSUE TITLE
Can't `go get` honeybadger-go

### ISSUE THREAD

**Issue by mattjmcnaughton** [honeybadger-io/honeybadger-go#17]
When I try to run `go get honeybadger-io/honeybadger-go`, I get

```bash
github.com/honeybadger-io/honeybadger-go/notice.go:101: undefined: load.LoadAvg
```

`load` is from [shirou/gopsutil](https://github.com/shirou/gopsutil). I think the problem is that `gopsutil` recently updated to `v2` and when doing so changed `load.LoadAvg` to just `load.Avg`, as seen in this [file](https://github.com/shirou/gopsutil/blob/master/v2migration.sh). It appears that `honeybadger-go` isn't using Godeps to vendor dependencies, so I think it was automatically trying to get the latest version of `shirou/gopsutil`, which now defines a new api. At least I think this could be what's going on, but I'm not positive.

Looking forward to using honeybadger on my go project!

**Comment by joshuap** [comment]
@mattjmcnaughton #16 should fix this issue -- can you try it again? Sorry for the hassle!
