### ISSUE TITLE
Latest v.0.2.0 tag doesn't follow semver standard

### ISSUE THREAD

**Issue by jamietsao** [honeybadger-io/honeybadger-go#26]
The 0.2.0 tag doesn't follow semver standards (should be `v0.2.0` instead of `v.0.2.0`), so as a result the `dep` (https://github.com/golang/dep) dependency management tool isn't picking up the latest version correctly.  It uses `v0.1.0` instead (which IS tagged correctly)

**Comment by joshuap** [comment]
@jamietsao sorry for the delay; I've updated the tag. Good catch.
