### ISSUE TITLE
Can't access the original error in before notify.

### ISSUE THREAD

**Issue by james-lawrence** [honeybadger-io/honeybadger-go#48]
## What are the steps to reproduce this issue?
```
honeybadger.Notice(MyErrorf("example"))

honeybadger.BeforeNotify(func(notice *honeybadger.Notice) error {
   log.Printf("%T\n", notice.Error) // is a honeybadger.Error which doesn't expose the underlying error.
   return nil
})
```

## What happens?
before notify handlers receive a honeybadger.Notice, but the error being wrapped isn't accessible.

## What were you expecting to happen?
I'd expect to be able to access the underlying cause using [stdlib functions](https://pkg.go.dev/errors) like unwrap, is, as. I'd also expect to be able to control the stack trace from error provided to the notice function.

## What versions are you using?
**Operating System:** linux
**Package Version:** v0.6.0
**Go Version:** 1.21

**Comment by subzero10** [comment]
Should be fixed with `v0.6.1`!
